spring:
  data:
    mongodb:
      uri: your_mongo_db_uri
      database: Employee
  mail:
    host: smtp.gmail.com
    port: 25
    username: your_mai
    password: your_pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8000
