spring:
  data:
    mongodb:
      uri: mongodb+srv://mradulsingh:mradulsingh@cluster1.t8prj2e.mongodb.net/
      database: Employee
  mail:
    host: smtp.gmail.com
    port: 25
    username: u4271398@gmail.com
    password: drir crht qxta snhy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8005